<%@ Page Language="C#" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
30 Build Your Own ASP.NET 4 Website Using C# & VB
www.it-ebooks.info
<script runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        myTimeLabel.Text = DateTime.Now.ToString();
    }
    private int foo()
    {
        return 23;
    }
</script>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Welcome to Build Your Own ASP.NET 4 Web Site!</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <p>Hello there!</p>
            <p>
                The time is now:
                <%-- Display the current date and time --%>
                <asp:Label ID="myTimeLabel" runat="server" />
            </p>
            <p>
                <%-- Declare the title as string and set it --%>
                <% string Title = "This is generated by a code render block.";
                    string test2 = "5 is > 3";%>
                <%= Title + "<br>" + test2 + "<br>" + foo() %>
                <%: "5 is > 3" %>
            </p>
        </div>
    </form>
</body>
</html>
